services:
  - type: web
    name: agrizone
    env: python
    buildCommand: "./build.sh"
    startCommand: "gunicorn agrizone.wsgi:application"
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: False
      - key: OPENWEATHER_API_KEY
        sync: false
      - key: OPENAI_API_KEY
        sync: false
      - key: EMAIL_HOST_PASSWORD
        sync: false
